-
  name: Playbook to change file and directory permissions
  hosts: all
  become: yes
  vars:
    DIR: '{{ target_dir }}'
    FILE: '{{ target_file }}'
    PERMISSIONS: '{{ number }}'
    OWNER: '{{ target_owner }}'
    GROUP: '{{ target_group }}'

  tasks: 

    - name: Checking that it is not a system mount point
      fail: 
        msg: "You can not change permissions on system mount points, please contact to de server administrator"
      when: DIR in ["/boot", "/etc", "/var", "/tmp", "/usr", "/", "/opt"]

    - name: Checking if the directory exists
      stat: 
        path: '{{ DIR }}'
      register: dir_status

    - name: Checking if the file exists
      stat: 
        path: '{{ FILE }}'
      register: file_status

    - name: Report if directory exists 
      debug: 
        msg: "Directory {{ DIR }} is present on the server"
      when: dir_status.stat.exists

    - name: Report if file exists
      debug:
        msg: "File {{ FILE }} is present on the server" 
      when: file_status.stat.exists

    - name: Applying new permissions
      file: 
          path: '{{ DIR }}/{{ FILE }}'
          state: file
          mode: '0{{ PERMISSIONS }}'
          owner: '{{ OWNER }}'
          group: '{{ GROUP }}'

    - name: Applying permissions recursively
      file: 
          path: '{{ DIR }}'
          mode: '0{{ PERMISSIONS }}'
          owner: '{{ OWNER }}'
          group: '{{ GROUP }}'
          recurse: yes